[
    { "dice": [1], "min": 2, "expected": "Falha Crítica" },
    { "dice": [1], "min": 3, "expected": "Falha Crítica" },
    { "dice": [1], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1], "min": 6, "expected": "Falha Crítica" },
    { "dice": [2], "min": 2, "expected": "Sucesso" },
    { "dice": [2], "min": 3, "expected": "Falha" },
    { "dice": [2], "min": 4, "expected": "Falha" },
    { "dice": [2], "min": 5, "expected": "Falha" },
    { "dice": [2], "min": 6, "expected": "Falha" },
    { "dice": [3], "min": 2, "expected": "Sucesso" },
    { "dice": [3], "min": 3, "expected": "Sucesso" },
    { "dice": [3], "min": 4, "expected": "Falha" },
    { "dice": [3], "min": 5, "expected": "Falha" },
    { "dice": [3], "min": 6, "expected": "Falha" },
    { "dice": [4], "min": 2, "expected": "Sucesso" },
    { "dice": [4], "min": 3, "expected": "Sucesso" },
    { "dice": [4], "min": 4, "expected": "Sucesso" },
    { "dice": [4], "min": 5, "expected": "Falha" },
    { "dice": [4], "min": 6, "expected": "Falha" },
    { "dice": [5], "min": 2, "expected": "Sucesso" },
    { "dice": [5], "min": 3, "expected": "Sucesso" },
    { "dice": [5], "min": 4, "expected": "Sucesso" },
    { "dice": [5], "min": 5, "expected": "Sucesso" },
    { "dice": [5], "min": 6, "expected": "Falha" },
    { "dice": [6], "min": 2, "expected": "Sucesso" },
    { "dice": [6], "min": 3, "expected": "Sucesso" },
    { "dice": [6], "min": 4, "expected": "Sucesso" },
    { "dice": [6], "min": 5, "expected": "Sucesso" },
    { "dice": [6], "min": 6, "expected": "Sucesso" },
    { "dice": [1, 1], "min": 2, "expected": "Falha Crítica" },
    { "dice": [1, 1], "min": 3, "expected": "Falha Crítica" },
    { "dice": [1, 1], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 1], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 1], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 2], "min": 2, "expected": "Falha" },
    { "dice": [1, 2], "min": 3, "expected": "Falha Crítica" },
    { "dice": [1, 2], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 2], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 2], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 3], "min": 2, "expected": "Falha" },
    { "dice": [1, 3], "min": 3, "expected": "Falha" },
    { "dice": [1, 3], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 3], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 3], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 4], "min": 2, "expected": "Falha" },
    { "dice": [1, 4], "min": 3, "expected": "Falha" },
    { "dice": [1, 4], "min": 4, "expected": "Falha" },
    { "dice": [1, 4], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 4], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 5], "min": 2, "expected": "Falha" },
    { "dice": [1, 5], "min": 3, "expected": "Falha" },
    { "dice": [1, 5], "min": 4, "expected": "Falha" },
    { "dice": [1, 5], "min": 5, "expected": "Falha" },
    { "dice": [1, 5], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 6], "min": 2, "expected": "Parcial" },
    { "dice": [1, 6], "min": 3, "expected": "Parcial" },
    { "dice": [1, 6], "min": 4, "expected": "Parcial" },
    { "dice": [1, 6], "min": 5, "expected": "Parcial" },
    { "dice": [1, 6], "min": 6, "expected": "Parcial" },
    { "dice": [2, 2], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 2], "min": 3, "expected": "Falha" },
    { "dice": [2, 2], "min": 4, "expected": "Falha" },
    { "dice": [2, 2], "min": 5, "expected": "Falha" },
    { "dice": [2, 2], "min": 6, "expected": "Falha" },
    { "dice": [2, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 3], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 3], "min": 4, "expected": "Falha" },
    { "dice": [2, 3], "min": 5, "expected": "Falha" },
    { "dice": [2, 3], "min": 6, "expected": "Falha" },
    { "dice": [2, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 4], "min": 5, "expected": "Falha" },
    { "dice": [2, 4], "min": 6, "expected": "Falha" },
    { "dice": [2, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 5], "min": 6, "expected": "Falha" },
    { "dice": [2, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [3, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 3], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 3], "min": 4, "expected": "Falha" },
    { "dice": [3, 3], "min": 5, "expected": "Falha" },
    { "dice": [3, 3], "min": 6, "expected": "Falha" },
    { "dice": [3, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 4], "min": 5, "expected": "Falha" },
    { "dice": [3, 4], "min": 6, "expected": "Falha" },
    { "dice": [3, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 5], "min": 6, "expected": "Falha" },
    { "dice": [3, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [4, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 4], "min": 5, "expected": "Falha" },
    { "dice": [4, 4], "min": 6, "expected": "Falha" },
    { "dice": [4, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [4, 5], "min": 6, "expected": "Falha" },
    { "dice": [4, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [4, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [5, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [5, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [5, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [5, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [5, 5], "min": 6, "expected": "Falha" },
    { "dice": [5, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [5, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [5, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [5, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [5, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [6, 6], "min": 2, "expected": "Primoroso" },
    { "dice": [6, 6], "min": 3, "expected": "Primoroso" },
    { "dice": [6, 6], "min": 4, "expected": "Primoroso" },
    { "dice": [6, 6], "min": 5, "expected": "Primoroso" },
    { "dice": [6, 6], "min": 6, "expected": "Primoroso" },
    { "dice": [1, 1, 1], "min": 2, "expected": "Falha Crítica" },
    { "dice": [1, 1, 1], "min": 3, "expected": "Falha Crítica" },
    { "dice": [1, 1, 1], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 1, 1], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 1, 1], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 1, 2], "min": 2, "expected": "Falha" },
    { "dice": [1, 1, 2], "min": 3, "expected": "Falha Crítica" },
    { "dice": [1, 1, 2], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 1, 2], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 1, 2], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 1, 3], "min": 2, "expected": "Falha" },
    { "dice": [1, 1, 3], "min": 3, "expected": "Falha" },
    { "dice": [1, 1, 3], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 1, 3], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 1, 3], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 1, 4], "min": 2, "expected": "Falha" },
    { "dice": [1, 1, 4], "min": 3, "expected": "Falha" },
    { "dice": [1, 1, 4], "min": 4, "expected": "Falha" },
    { "dice": [1, 1, 4], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 1, 4], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 1, 5], "min": 2, "expected": "Falha" },
    { "dice": [1, 1, 5], "min": 3, "expected": "Falha" },
    { "dice": [1, 1, 5], "min": 4, "expected": "Falha" },
    { "dice": [1, 1, 5], "min": 5, "expected": "Falha" },
    { "dice": [1, 1, 5], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 1, 6], "min": 2, "expected": "Falha" },
    { "dice": [1, 1, 6], "min": 3, "expected": "Falha" },
    { "dice": [1, 1, 6], "min": 4, "expected": "Falha" },
    { "dice": [1, 1, 6], "min": 5, "expected": "Falha" },
    { "dice": [1, 1, 6], "min": 6, "expected": "Falha" },
    { "dice": [1, 2, 2], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 2, 2], "min": 3, "expected": "Falha Crítica" },
    { "dice": [1, 2, 2], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 2, 2], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 2, 2], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 2, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 2, 3], "min": 3, "expected": "Falha" },
    { "dice": [1, 2, 3], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 2, 3], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 2, 3], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 2, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 2, 4], "min": 3, "expected": "Falha" },
    { "dice": [1, 2, 4], "min": 4, "expected": "Falha" },
    { "dice": [1, 2, 4], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 2, 4], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 2, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 2, 5], "min": 3, "expected": "Falha" },
    { "dice": [1, 2, 5], "min": 4, "expected": "Falha" },
    { "dice": [1, 2, 5], "min": 5, "expected": "Falha" },
    { "dice": [1, 2, 5], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 2, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 2, 6], "min": 3, "expected": "Parcial" },
    { "dice": [1, 2, 6], "min": 4, "expected": "Parcial" },
    { "dice": [1, 2, 6], "min": 5, "expected": "Parcial" },
    { "dice": [1, 2, 6], "min": 6, "expected": "Parcial" },
    { "dice": [1, 3, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 3, 3], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 3, 3], "min": 4, "expected": "Falha Crítica" },
    { "dice": [1, 3, 3], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 3, 3], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 3, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 3, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 3, 4], "min": 4, "expected": "Falha" },
    { "dice": [1, 3, 4], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 3, 4], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 3, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 3, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 3, 5], "min": 4, "expected": "Falha" },
    { "dice": [1, 3, 5], "min": 5, "expected": "Falha" },
    { "dice": [1, 3, 5], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 3, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 3, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 3, 6], "min": 4, "expected": "Parcial" },
    { "dice": [1, 3, 6], "min": 5, "expected": "Parcial" },
    { "dice": [1, 3, 6], "min": 6, "expected": "Parcial" },
    { "dice": [1, 4, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 4, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 4, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [1, 4, 4], "min": 5, "expected": "Falha Crítica" },
    { "dice": [1, 4, 4], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 4, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 4, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 4, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [1, 4, 5], "min": 5, "expected": "Falha" },
    { "dice": [1, 4, 5], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 4, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 4, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 4, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [1, 4, 6], "min": 5, "expected": "Parcial" },
    { "dice": [1, 4, 6], "min": 6, "expected": "Parcial" },
    { "dice": [1, 5, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 5, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 5, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [1, 5, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [1, 5, 5], "min": 6, "expected": "Falha Crítica" },
    { "dice": [1, 5, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 5, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 5, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [1, 5, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [1, 5, 6], "min": 6, "expected": "Parcial" },
    { "dice": [1, 6, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [1, 6, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [1, 6, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [1, 6, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [1, 6, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [2, 2, 2], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 2, 2], "min": 3, "expected": "Falha" },
    { "dice": [2, 2, 2], "min": 4, "expected": "Falha" },
    { "dice": [2, 2, 2], "min": 5, "expected": "Falha" },
    { "dice": [2, 2, 2], "min": 6, "expected": "Falha" },
    { "dice": [2, 2, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 2, 3], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 2, 3], "min": 4, "expected": "Falha" },
    { "dice": [2, 2, 3], "min": 5, "expected": "Falha" },
    { "dice": [2, 2, 3], "min": 6, "expected": "Falha" },
    { "dice": [2, 2, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 2, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 2, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 2, 4], "min": 5, "expected": "Falha" },
    { "dice": [2, 2, 4], "min": 6, "expected": "Falha" },
    { "dice": [2, 2, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 2, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 2, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 2, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 2, 5], "min": 6, "expected": "Falha" },
    { "dice": [2, 2, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 2, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 2, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 2, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 2, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [2, 3, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 3, 3], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 3, 3], "min": 4, "expected": "Falha" },
    { "dice": [2, 3, 3], "min": 5, "expected": "Falha" },
    { "dice": [2, 3, 3], "min": 6, "expected": "Falha" },
    { "dice": [2, 3, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 3, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 3, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 3, 4], "min": 5, "expected": "Falha" },
    { "dice": [2, 3, 4], "min": 6, "expected": "Falha" },
    { "dice": [2, 3, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 3, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 3, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 3, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 3, 5], "min": 6, "expected": "Falha" },
    { "dice": [2, 3, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 3, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 3, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 3, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 3, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [2, 4, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 4, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 4, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 4, 4], "min": 5, "expected": "Falha" },
    { "dice": [2, 4, 4], "min": 6, "expected": "Falha" },
    { "dice": [2, 4, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 4, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 4, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 4, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 4, 5], "min": 6, "expected": "Falha" },
    { "dice": [2, 4, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 4, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 4, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 4, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 4, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [2, 5, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 5, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 5, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 5, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 5, 5], "min": 6, "expected": "Falha" },
    { "dice": [2, 5, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [2, 5, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [2, 5, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [2, 5, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [2, 5, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [2, 6, 6], "min": 2, "expected": "Primoroso" },
    { "dice": [2, 6, 6], "min": 3, "expected": "Primoroso" },
    { "dice": [2, 6, 6], "min": 4, "expected": "Primoroso" },
    { "dice": [2, 6, 6], "min": 5, "expected": "Primoroso" },
    { "dice": [2, 6, 6], "min": 6, "expected": "Primoroso" },
    { "dice": [3, 3, 3], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 3, 3], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 3, 3], "min": 4, "expected": "Falha" },
    { "dice": [3, 3, 3], "min": 5, "expected": "Falha" },
    { "dice": [3, 3, 3], "min": 6, "expected": "Falha" },
    { "dice": [3, 3, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 3, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 3, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 3, 4], "min": 5, "expected": "Falha" },
    { "dice": [3, 3, 4], "min": 6, "expected": "Falha" },
    { "dice": [3, 3, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 3, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 3, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 3, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 3, 5], "min": 6, "expected": "Falha" },
    { "dice": [3, 3, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 3, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 3, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 3, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 3, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [3, 4, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 4, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 4, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 4, 4], "min": 5, "expected": "Falha" },
    { "dice": [3, 4, 4], "min": 6, "expected": "Falha" },
    { "dice": [3, 4, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 4, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 4, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 4, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 4, 5], "min": 6, "expected": "Falha" },
    { "dice": [3, 4, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 4, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 4, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 4, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 4, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [3, 5, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 5, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 5, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 5, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 5, 5], "min": 6, "expected": "Falha" },
    { "dice": [3, 5, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [3, 5, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [3, 5, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [3, 5, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [3, 5, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [3, 6, 6], "min": 2, "expected": "Primoroso" },
    { "dice": [3, 6, 6], "min": 3, "expected": "Primoroso" },
    { "dice": [3, 6, 6], "min": 4, "expected": "Primoroso" },
    { "dice": [3, 6, 6], "min": 5, "expected": "Primoroso" },
    { "dice": [3, 6, 6], "min": 6, "expected": "Primoroso" },
    { "dice": [4, 4, 4], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 4, 4], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 4, 4], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 4, 4], "min": 5, "expected": "Falha" },
    { "dice": [4, 4, 4], "min": 6, "expected": "Falha" },
    { "dice": [4, 4, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 4, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 4, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 4, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [4, 4, 5], "min": 6, "expected": "Falha" },
    { "dice": [4, 4, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 4, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 4, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 4, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [4, 4, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [4, 5, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 5, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 5, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 5, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [4, 5, 5], "min": 6, "expected": "Falha" },
    { "dice": [4, 5, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [4, 5, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [4, 5, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [4, 5, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [4, 5, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [4, 6, 6], "min": 2, "expected": "Primoroso" },
    { "dice": [4, 6, 6], "min": 3, "expected": "Primoroso" },
    { "dice": [4, 6, 6], "min": 4, "expected": "Primoroso" },
    { "dice": [4, 6, 6], "min": 5, "expected": "Primoroso" },
    { "dice": [4, 6, 6], "min": 6, "expected": "Primoroso" },
    { "dice": [5, 5, 5], "min": 2, "expected": "Sucesso" },
    { "dice": [5, 5, 5], "min": 3, "expected": "Sucesso" },
    { "dice": [5, 5, 5], "min": 4, "expected": "Sucesso" },
    { "dice": [5, 5, 5], "min": 5, "expected": "Sucesso" },
    { "dice": [5, 5, 5], "min": 6, "expected": "Falha" },
    { "dice": [5, 5, 6], "min": 2, "expected": "Sucesso" },
    { "dice": [5, 5, 6], "min": 3, "expected": "Sucesso" },
    { "dice": [5, 5, 6], "min": 4, "expected": "Sucesso" },
    { "dice": [5, 5, 6], "min": 5, "expected": "Sucesso" },
    { "dice": [5, 5, 6], "min": 6, "expected": "Sucesso" },
    { "dice": [5, 6, 6], "min": 2, "expected": "Primoroso" },
    { "dice": [5, 6, 6], "min": 3, "expected": "Primoroso" },
    { "dice": [5, 6, 6], "min": 4, "expected": "Primoroso" },
    { "dice": [5, 6, 6], "min": 5, "expected": "Primoroso" },
    { "dice": [5, 6, 6], "min": 6, "expected": "Primoroso" },
    { "dice": [6, 6, 6], "min": 2, "expected": "Espetacular" },
    { "dice": [6, 6, 6], "min": 3, "expected": "Espetacular" },
    { "dice": [6, 6, 6], "min": 4, "expected": "Espetacular" },
    { "dice": [6, 6, 6], "min": 5, "expected": "Espetacular" },
    { "dice": [6, 6, 6], "min": 6, "expected": "Espetacular" },
    { "dice": [1], "min": "hidden", "expected": "Falha Crítica" },
    { "dice": [2], "min": "hidden", "expected": "Passei?" },
    { "dice": [3], "min": "hidden", "expected": "Passei?" },
    { "dice": [4], "min": "hidden", "expected": "Passei?" },
    { "dice": [5], "min": "hidden", "expected": "Passei?" },
    { "dice": [6], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 1], "min": "hidden", "expected": "Falha Crítica" },
    { "dice": [1, 2], "min": "hidden", "expected": "Falha" },
    { "dice": [1, 3], "min": "hidden", "expected": "Falha" },
    { "dice": [1, 4], "min": "hidden", "expected": "Falha" },
    { "dice": [1, 5], "min": "hidden", "expected": "Falha" },
    { "dice": [1, 6], "min": "hidden", "expected": "Parcial?" },
    { "dice": [2, 2], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [5, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [5, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [6, 6], "min": "hidden", "expected": "Primoroso" },
    { "dice": [1, 1, 1], "min": "hidden", "expected": "Falha Crítica" },
    { "dice": [1, 1, 2], "min": "hidden", "expected": "Falha?" },
    { "dice": [1, 1, 3], "min": "hidden", "expected": "Falha?" },
    { "dice": [1, 1, 4], "min": "hidden", "expected": "Falha?" },
    { "dice": [1, 1, 5], "min": "hidden", "expected": "Falha?" },
    { "dice": [1, 1, 6], "min": "hidden", "expected": "Falha Crítica" },
    { "dice": [1, 2, 2], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 2, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 2, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 2, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 2, 6], "min": "hidden", "expected": "Parcial?" },
    { "dice": [1, 3, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 3, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 3, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 3, 6], "min": "hidden", "expected": "Parcial?" },
    { "dice": [1, 4, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 4, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 4, 6], "min": "hidden", "expected": "Parcial?" },
    { "dice": [1, 5, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [1, 5, 6], "min": "hidden", "expected": "Parcial?" },
    { "dice": [1, 6, 6], "min": "hidden", "expected": "Parcial?" },
    { "dice": [2, 2, 2], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 2, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 2, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 2, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 2, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 3, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 3, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 3, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 3, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [2, 4, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 4, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 4, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [2, 5, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [2, 5, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [2, 6, 6], "min": "hidden", "expected": "Primoroso" },
    { "dice": [3, 3, 3], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 3, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 3, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 3, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [3, 4, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 4, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 4, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [3, 5, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [3, 5, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [3, 6, 6], "min": "hidden", "expected": "Primoroso" },
    { "dice": [4, 4, 4], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 4, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 4, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 5, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 5, 6], "min": "hidden", "expected": "Passei?" },
    { "dice": [4, 6, 6], "min": "hidden", "expected": "Primoroso" },
    { "dice": [5, 5, 5], "min": "hidden", "expected": "Passei?" },
    { "dice": [5, 5, 6], "min": "hidden", "expected": "Sucesso?" },
    { "dice": [5, 6, 6], "min": "hidden", "expected": "Primoroso" },
    { "dice": [6, 6, 6], "min": "hidden", "expected": "Espetacular" }
]